#ifndef __RESOURCE_H__
#define __RESOURCE_H__

#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

// Acceleration
#define IDA_MAIN 1

// Dialogs
#define IDD_MAIN 100
#define IDD_PAGE_PING 101
#define IDD_PAGE_SPEEDMETER 102
#define IDD_PAGE_URLDECODER 103
#define IDD_PAGE_HOSTADDR 104
#define IDD_PAGE_URLINFO 105
#define IDD_PAGE_WHOIS 106
#define IDD_PAGE_IP 107
#define IDD_PAGE_SHAREDINFO 108
#define IDD_PAGE_SYSINFO 109
#define IDD_PAGE_TCP_STATISTIC 110
#define IDD_PAGE_UDP_STATISTIC 111
#define IDD_PAGE_ICMP_STATISTIC 112
#define IDD_PAGE_IP_STATISTIC 113

// Menu Id
#define IDM_MAIN 100
#define IDM_LISTVIEW 101
#define IDM_COPY 102
#define IDM_SELECT_ALL 103

//#define IDM_COPY_VALUE 103
//#define IDM_SAVE_AS 104

// Main Menu
#define IDM_EXIT 104
#define IDM_ALWAYSONTOP_CHK 105
#define IDM_CHECKUPDATES_CHK 106
#define IDM_WEBSITE 107
#define IDM_CHECKUPDATES 108
#define IDM_ABOUT 109
#define IDM_REFRESH 110
#define IDM_ZOOM 111

#define IDX_LANGUAGE 1000

// Main Dlg
#define IDC_ITEMLIST 112
#define IDC_STATUSBAR 113

// Settings Dlg
#define IDC_NAV 114
#define IDC_RESET 115
#define IDC_CLOSE 116

// Ping Page
#define IDC_PING_HOST 117
#define IDC_PING_RETRIES 118
#define IDC_PING_UPDOWN 119
#define IDC_PING_RESULT 120
#define IDC_PING_START 121
#define IDC_PING_CLEAR 122

// Speed Meter Page
#define IDC_SPEEDMETER_LINK 123
#define IDC_SPEEDMETER_LIMIT 124
#define IDC_SPEEDMETER_UPDOWN 125
#define IDC_SPEEDMETER_RESULT 126
#define IDC_SPEEDMETER_START 127
#define IDC_SPEEDMETER_CLEAR 128

// Url Decoder Page
#define IDC_URLDECODER_LINK 129
#define IDC_URLDECODER_RESULT 130
#define IDC_URLDECODER_START 131
#define IDC_URLDECODER_CLEAR 132

// Host Address Page
#define IDC_HOSTADDR_HOST 133
#define IDC_HOSTADDR_RESULT 134
#define IDC_HOSTADDR_START 135
#define IDC_HOSTADDR_CLEAR 136

// Url Info Page
#define IDC_URLINFO_LINK 137
#define IDC_URLINFO_RESULT 138
#define IDC_URLINFO_HEADER 139
#define IDC_URLINFO_HEADER_CHK 140
#define IDC_URLINFO_START 141
#define IDC_URLINFO_CLEAR 142

// Ip Page
#define IDC_IP_RESULT 143
#define IDC_IP_EXTERNAL_CHK 144
#define IDC_IP_REFRESH 145

// Whois Page
#define IDC_WHOIS_HOST 146
#define IDC_WHOIS_SERVER 147
#define IDC_WHOIS_RESULT 148
#define IDC_WHOIS_START 149
#define IDC_WHOIS_CLEAR 150

// System Info Page
#define IDC_SYSINFO 151

// Tcp Statistic Page
#define IDC_TCP_STATISTIC 152

// Udp Statistic Page
#define IDC_UDP_STATISTIC 153

// Icmp Statistic Page
#define IDC_ICMP_STATISTIC 154

// Ip Statistic Page
#define IDC_IP_STATISTIC 155


#define IDC_SHAREDINFO 156
#define IDC_SHAREDINFO_START 157
#define IDC_SHAREDINFO_CLEAR 158

#define IDS_FILE 1
#define IDS_SETTINGS 2
#define IDS_HELP 3
#define IDS_EXIT 4
#define IDS_ALWAYSONTOP_CHK 5
#define IDS_CHECKUPDATES_CHK 6
#define IDS_LANGUAGE 7
#define IDS_WEBSITE 8
#define IDS_CHECKUPDATES 9
#define IDS_DONATE 10
#define IDS_ABOUT 11
#define IDS_CLOSE 12
#define IDS_CATEGORY_TOOLS 13
#define IDS_CATEGORY_INFORMATION 14
#define IDS_CATEGORY_STATISTICS 15
#define IDS_TOOL_PING 16
#define IDS_TOOL_PING_INFO 17
#define IDS_TOOL_SPEED 18
#define IDS_TOOL_SPEED_INFO 19
#define IDS_TOOL_DECODER 20
#define IDS_TOOL_DECODER_INFO 21
#define IDS_TOOL_INFORMATION 22
#define IDS_TOOL_INFORMATION_INFO 23
#define IDS_TOOL_HOSTADDRESS 24
#define IDS_TOOL_HOSTADDRESS_INFO 25
#define IDS_TOOL_WHOIS 26
#define IDS_TOOL_WHOIS_INFO 27
#define IDS_TOOL_IP 28
#define IDS_TOOL_IP_INFO 29
#define IDS_TOOL_SHARED 30
#define IDS_TOOL_SHARED_INFO 31
#define IDS_TOOL_SYSTEM 32
#define IDS_TOOL_SYSTEM_INFO 33
#define IDS_TOOL_TCP 34
#define IDS_TOOL_TCP_INFO 35
#define IDS_TOOL_UDP 36
#define IDS_TOOL_UDP_INFO 37
#define IDS_TOOL_ICMP 38
#define IDS_TOOL_ICMP_INFO 39
#define IDS_TOOL_IPSTATS 40
#define IDS_TOOL_IPSTATS_INFO 41

// Icons
#define IDI_MAIN 100
#define IDI_FOLDER 101
#define IDI_FOLDER_CURRENT 102
#define IDI_SUCCESS 103
#define IDI_FAULT 104

#endif
